global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'bookshare-monitor'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']

# Rule files (optional)
# rule_files:
#   - "alerts.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Laravel application metrics
  - job_name: 'laravel-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']
        labels:
          app: 'bookshare'
          env: 'local'
    # If running on Windows with Docker Desktop, use host.docker.internal
    # If on Linux, use your host IP or service name

  # Node exporter for system metrics (optional - uncomment if you add node_exporter)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

  # MySQL exporter for database metrics (optional)
  # - job_name: 'mysql'
  #   static_configs:
  #     - targets: ['mysql-exporter:9104']
